# Generated by Django 4.1.7 on 2023-04-06 10:16

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('ds4rs_app1', '0002_ndbitask_delete_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LSTMapTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.CharField(max_length=255)),
                ('toDate', models.CharField(max_length=255)),
                ('cloudCover', models.CharField(max_length=5)),
                ('satelliteName', models.CharField(max_length=255)),
                ('aoiShape', models.FileField(upload_to=pathlib.PureWindowsPath('D:/3. Projects/dash/ds4rs_main_app/subdir'))),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ndbitask',
            name='aoiShape',
            field=models.FileField(upload_to='D:\\3. Projects\\dash\\ds4rs_main_app\\public\\ds4rs_app1\\shapefiles'),
        ),
    ]
