# Generated by Django 4.1.7 on 2023-04-06 10:35

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('ds4rs_app1', '0003_lstmaptask_alter_ndbitask_aoishape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lstmaptask',
            name='aoiShape',
            field=models.FileField(upload_to=pathlib.PureWindowsPath('D:/3. Projects/dash/ds4rs_main_app/public/ds4rs_app1/LSTMapTasksshapefiles')),
        ),
    ]
