# Generated by Django 4.1.7 on 2023-04-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds4rs_app1', '0005_alter_lstmaptask_aoishape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lstmaptask',
            name='aoiShape',
            field=models.FileField(upload_to='D:\\3. Projects\\dash\\ds4rs_main_app\\public\\ds4rs_app1\\LSTMapTasksshapefiles'),
        ),
    ]
